apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-var
  namespace: default # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
