apiVersion: v1
kind: Service
metadata:
  name: "websocket"
  namespace: default # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: websocket

